require: rubocop-rails

AllCops:
  Include:
    - '/**/*.arb'
    - '/**/*.rb'
    - '/**/*.gemfile'
    - '/**/*.gemspec'
    - '/**/*.rake'
    - '/**/*.ru'
    - '/Gemfile'
    - '/Rakefile'

  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'vendor/**/*'
    - 'bin/*'

Metrics/LineLength:
  Max: 140

Documentation:
  Enabled: false
