require: rubocop-rails

AllCops:
  Include:
    - '**/*.arb'
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'

  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'vendor/**/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140
