require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Include:
    - '**/*.arb'
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'

  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'vendor/**/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb

Metrics/LineLength:
  Max: 140

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - app/admin/*.rb
    - config/environments/*.rb
    - config/routes.rb
    - lib/tasks/national_budgets/*.rake
    - spec/**/*_spec.rb
    - spec/factories/*.rb

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*_spec.rb

RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*_spec.rb

Style/TrivialAccessors:
  Exclude:
    - lib/tasks/national_budgets/*.rake
