inherit_from: .rubocop_todo.yml

AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
    - vendor/**/* # Circle adds the rubies here
inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml
