require: rubocop-rails

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**
    - db/**
    - config/**
    - script/**
    - vendor/**/* # Circle adds the rubies here

Metrics/LineLength:
  Max: 140

Documentation:
  Enabled: false
